### ISSUE TITLE
Comment field in Whitelist/Blacklist makes the entry stop working

### ISSUE THREAD

**Issue by DinoBrdar92** [pi-hole/web#2278] opened 2022-07-31 23:52 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---

**Expected behavior:**

`Whitelist and Blacklist working as they should when I change my entries' comments`

**Actual behavior:**

`After changing comments for my Whitelist/Blacklist entries, Pihole behaves as if they don't exist anymore`

**Steps to reproduce:**

`1. Add something to Blacklist or Whitelist by pressing the button on the right inside Query Log (recommended to try something that sends requests often, or that you can manually induce the request for)
2. Refresh Query Log to see if it's working properly
3. Go to Blacklist/Whitelist and edit the comment of the entry
4. Go back to the Query Log and see that the entry isn't working anymore = profit`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/jNJgwBGi/`

**Troubleshooting undertaken, and/or other relevant information:**

`Removed everything from Whitelist/Blacklist, took screenshots and copied to text editor, then entered everything back in.`

**Comment by jfb-pihole** [comment] 2022-08-01 03:30
Appears to be a duplicate of:

https://github.com/pi-hole/AdminLTE/issues/2260

**Closed as completed** 2022-08-01 03:30 UTC
