### ISSUE TITLE
Number of domain in adlist only shows exact match domain not ABP style domain

### ISSUE THREAD

**Issue by rrhul0** [pi-hole/web#2638] opened 2023-07-16 05:25 UTC
### Versions

- Pi-hole version is v5.17.1 (Latest: v5.17.1)
- AdminLTE version is v5.20.1 (Latest: v5.20.1)
- FTL version is v5.23 (Latest: v5.23)

### Platform

- OS and version:  N/A

- Platform:  Docker

### Expected behavior

After updating the gravity with an ABP style block list. Information about adlist at adlist page shows 0 domains in the adlist while the adlist clearly have a lot of ABP style blocked domains which can also be confirmed by the gravity update logs.

gravity update log
```
  [i] Target: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 827103 ABP-style domains (ignored 0 non-domain entries)
  [i] List has been updated

  [i] Target: https://big.oisd.nl
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 251277 ABP-style domains (ignored 0 non-domain entries)
  [i] List has been updated
```

info of these adlists at ad lists page (after update)
![Screenshot 2023-07-16 at 10 41 21](https://github.com/pi-hole/AdminLTE/assets/72130755/fa17e32d-7852-480d-91b9-ab254f511ed1)

### Actual behavior / bug

There should also a new line in info of adlist which shows the number of ABP style blocked domains.

### Steps to reproduce

1. Add an adlist which has ABP style block domain.
2. Update gravity. If your adlist have some ABP style domain then in gravity output you can see it parse ABP style domains.
3. Now go to web ui of pi-hole then adlist page (if already was here just refresh). If you click on 'Green tick' of the adlist you will see the info about the adlist. In this adlist info there is no ABP style block domains.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment] 2023-07-16 05:57
Thanks for the report. This is a duplicate of https://github.com/pi-hole/FTL/issues/1573.

**Closed as completed by yubiuser** 2023-07-16 05:57 UTC
Labels: Duplicate
