### ISSUE TITLE
24hr activity graph takes long to draw after period of high client activity

### ISSUE THREAD

**Issue by frollic** [pi-hole/web#1623] opened 2020-10-26 10:30 UTC
### Versions
- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  patched version from https://github.com/pi-hole/FTL/issues/868

### Platform

- OS and version:  Centos 7
- Platform:  Oracle cloud x86_64

### Expected behavior

After and during a period of large amount of clients, the 24hr activity graph takes "forever" to display.

### Actual behavior / bug

Since my pi-hole is exposted to internet, I somtimes get unwanted guests and behaviours.
The other day there was a DDOS (I'd assume) going on, and the pihole served about 2000
clients during a period of ~24 hrs. 

The DNS request they were making were a know DDOS destination, and I was banning their 
IPs as soon as the requests came in (query [ANY] ..... ), most clients never managed to get 
more than 3 requests in before they were dropped by the FW. 
Never the less, even 1 request would add tho the grand total of clients during the 24hr window.

During the "attack" the 24 activity graph took forever to draw, but it was eventually displayed 
(took several minutes).

2000 clients * 10 requests / (24h * 60min)  = <14 requests/minute, so it shouldn't be a DNS 
performance issue.

If this is expected behaviour or not, I cannot tell, but it is acceptable, due to the amount traffic/clients.

Problem is, when the attack ended the graph *still* takes forever to draw. And when I say ended, I
don't mean right after, but after the whole 24hr DDOS attack window had passed, and I was back 
to 15ish clients or so.

It is fixable by restarting pihole-FTL, but it doesn't sound like the ideal solution.

I'm not sure how the graph is getting drawn/generated, but by the looks of it, the selection beeing
made isn't healthy.

There are no errors anywhere in the logs.

For obvious reasons, this problem is difficult to reproduce .... ;)

**Comment by DL6ER** [comment] 2020-11-08 17:09
Moving this bug ticket over to the web interface repo, as any message from the browser (regarding performance/hanging page) comes from Javascript issues. The data will already have been sent to your browser in this case and the issue is either with unpacking the data and/or with drawing the chart.

**Comment by ehb224** [comment] 2020-11-15 16:45
It seems that this might be related to issue  #1485 "A web page is slowing down your browser".  I have been having this problem since version 5.0 of the web interface with Firefox, Chrome, and Edge running Pihole on a Raspberry Pi 3b. The hang always occurs when trying to load the 24 hour client activity graph and I have discovered that flushing the logs is the only way to temporarily fix the problem for a day or two in my case.

**Comment by ehb224** [comment] 2020-11-15 16:52
I generated a debug token but I just recently cleared my logs so I don't know how useful it might be. https://tricorder.pi-hole.net/20dkaw8loj
I will generate another one and post it when the problem reoccurs if that is helpful.

**Comment by dschaper** [comment] 2020-11-15 17:00
How much memory have you allocated to PHP?

**Comment by ehb224** [comment] 2020-11-15 17:16
Mine is the default setting of 128M according to the  /etc/php/7.3/cgi/php.ini file.

**Comment by dschaper** [comment] 2020-11-15 17:17
Check the lighttpd logs (access and error) and see if there are warnings that memory can not be allocated.

**Comment by ehb224** [comment] 2020-11-15 17:39
I am unable to access the logs even after adding user pi to the group www-data. I can access the lighttpd directory with a sudo cd command but when I try to access the log files they come up  as blank ieven though they are not

**Comment by dschaper** [comment] 2020-11-15 17:42
`sudo -i` or `sudo -u` will bump you to root so you can execute commands.

**Comment by ehb224** [comment] 2020-11-15 18:19
Thanks! No memory allocation warnings in either file, although the access log is extremely large and it is possible that I missed something as I went through it with nano.

**Comment by dschaper** [comment] 2020-11-15 18:40
It will be in error.log, have you seen the issue happen since you started the new logs?

**Comment by ehb224** [comment] 2020-11-15 19:29
Not yet. I will have to wait a day or two before the problem starts again. Once it does I will check the error.log file and post here and also upload a new debug token.

**Comment by ehb224** [comment] 2020-11-18 19:06
Getting "A webpage is slowing down your browser" again and now it happens when "Total queries over last 24 hours" box is loading so the page remains unpopulated except for the 4 boxes across the top. it will eventually load if I wait long enough (3-5 minutes) and I keep clicking on the 'wait' button as the error message reappears. Past behavior is that the wait will get longer and longer and eventually the page will not load until I flush the logs. Same behavior in Chrome, Edge, and Opera, btw.
new debug token https://tricorder.pi-hole.net/lh07a0pcve
no  memory allocation errors in lighttpd error.log but there is this:
2020-11-15 14:43:47: (mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Undefined index: type in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 507

**Comment by ehb224** [comment] 2020-11-23 16:07
problem has gotten worse. Now stuck on loading 24 hour activity graph indefinitely. Here is the debug token I just generated:
https://tricorder.pi-hole.net/fe6oh03656

**Comment by ehb224** [comment] 2020-11-23 16:14
This is the current lighttpd error.log file:

2020-11-22 00:00:19: (server.c.1759) logfiles cycled UID = 0 PID = 27301

**Comment by dschaper** [comment] 2020-11-23 16:26
First:

There's no need to use IPv4 and IPv6 as localhost upstream servers. And I think you have the IPv6 upstream port wrong.

```plain
    PIHOLE_DNS_1=127.0.0.1#5335
    PIHOLE_DNS_2=::1#58335
```

If you're forwarding to a local `unbound` then remove the `::1` line, it's really not doing anything but adding to the troubles.

Second:

Don't use a globally accessible IPv6 address. Use a ULA address block, and really you don't need IPv6 on a LAN segment at all.

Third:

Your `locale` seems broken, what does the command

```plain
locale
```
print out to the terminal?

**Comment by dschaper** [comment] 2020-11-23 16:28
Also, get rid of `Managed by pihole-updatelists`. It's adding a ton of domains and garbage to your setup.

**Comment by ehb224** [comment] 2020-11-23 16:40
this is locale:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by dschaper** [comment] 2020-11-23 16:42
And the output from

```
ls -lac /var/log/lighttpd/
```
please?

**Comment by ehb224** [comment] 2020-11-23 16:50
ls -lac /var/log/lighttpd/
total 8316
drwxr-x--- 2 www-data www-data     560 Nov 23 11:23 .
drwxr-xr-x 6 root     root        1400 Nov 23 00:00 ..
-rw-r--r-- 1 www-data www-data  838541 Nov 23 11:49 access.log
-rw-r--r-- 1 www-data www-data 7463502 Nov 22 00:00 access.log.1
-rw-r--r-- 1 www-data www-data    2071 Nov 22 00:00 access.log.10.gz
-rw-r--r-- 1 www-data www-data   28515 Nov 22 00:00 access.log.11.gz
-rw-r--r-- 1 www-data www-data   10468 Nov 22 00:00 access.log.12.gz
-rw-r--r-- 1 www-data www-data    2035 Nov 22 00:00 access.log.2.gz
-rw-r--r-- 1 www-data www-data      90 Nov 22 00:00 access.log.3.gz
-rw-r--r-- 1 www-data www-data      81 Nov 22 00:00 access.log.4.gz
-rw-r--r-- 1 www-data www-data      96 Nov 22 00:00 access.log.5.gz
-rw-r--r-- 1 www-data www-data    2610 Nov 22 00:00 access.log.6.gz
-rw-r--r-- 1 www-data www-data     903 Nov 22 00:00 access.log.7.gz
-rw-r--r-- 1 www-data www-data   78568 Nov 22 00:00 access.log.8.gz
-rw-r--r-- 1 www-data www-data     109 Nov 22 00:00 access.log.9.gz
-rw-r--r-- 1 www-data www-data      74 Nov 22 00:00 error.log
-rw-r--r-- 1 www-data www-data     924 Nov 22 00:00 error.log.1
-rw-r--r-- 1 www-data www-data      88 Nov 22 00:00 error.log.10.gz
-rw-r--r-- 1 www-data www-data      89 Nov 22 00:00 error.log.11.gz
-rw-r--r-- 1 www-data www-data      85 Nov 22 00:00 error.log.12.gz
-rw-r--r-- 1 www-data www-data      89 Nov 22 00:00 error.log.2.gz
-rw-r--r-- 1 www-data www-data     149 Nov 22 00:00 error.log.3.gz
-rw-r--r-- 1 www-data www-data      87 Nov 22 00:00 error.log.4.gz
-rw-r--r-- 1 www-data www-data      87 Nov 22 00:00 error.log.5.gz
-rw-r--r-- 1 www-data www-data      86 Nov 22 00:00 error.log.6.gz
-rw-r--r-- 1 www-data www-data      88 Nov 22 00:00 error.log.7.gz
-rw-r--r-- 1 www-data www-data      88 Nov 22 00:00 error.log.8.gz
-rw-r--r-- 1 www-data www-data      87 Nov 22 00:00 error.log.9.gz

**Comment by dschaper** [comment] 2020-11-23 16:53
Okay, I suggest removing that IPv6 configuration (mostly because `unbound` isn't even listening on that port and address) and reset the lists back to stock. It doesn't look like there's any customization made, just the entries from that script that isn't helpful to have running.

Once you're back on stock then we can see if the problem is resolved and we can narrow the problem down to the IPv6 configuration or that 3rd party script.

**Comment by ehb224** [comment] 2020-11-23 17:00
I am also running:
Log2ram
https://github.com/jessedp/pihole5-list-tool
https://github.com/jacklul/pihole-updatelists (to automatically update lists)
Could one of these be causing the problems? 
I have removed the IPv6 configuration.
How do I reset the lists back to stock?

FWIW, this problem did not exist in 4.3, It started with the upgrade to 5.0.

**Comment by ehb224** [comment] 2020-11-25 04:08
back on stock. Just running log2ram but not pihole5-list-tool or pihole-updatelist scripts and have turned off IPv6 localhost. I flushed the logs and will see how it's running in about a week. As of right now it takes about 30-40 seconds for the 24 hour activity graph to load and then the rest of the page loads very quickly.

**Comment by ehb224** [comment] 2020-11-30 15:42
Everything seems to be working since the latest update. Load time for the dashboard is now approx. 12-15 seconds. Here is the latest debug token:
https://tricorder.pi-hole.net/0bh0phh311

**Closed as completed** 2022-01-16 19:14 UTC
Labels: Submitter Attention Required
