### ISSUE TITLE
encoded HTML displaying in DHCP tables

### ISSUE THREAD

**Issue by thedannywahl** [pi-hole/web#1524] opened 2020-07-22 16:17 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---

**Expected behavior:**

Unknown hosts in Active DHCP leases table (#HOSTS) should be italicized.

**Actual behavior:**

`em` element set via `jQuery.html()` is encoded resulting in display of text string '&lt;em&gt;Unknown&lt;/em&gt;' instead of decoded value '_Unknown_'

relevant commit: https://github.com/pi-hole/AdminLTE/commit/a99bfeaa6c751839c5ca3ffee4546a5051d29de9

**Steps to reproduce:**

* update to piHole v5.1.1
* add device to network w/o DHCP host name entry
* visit `/admin/settings.php?tab=piholedhcp`
* view "Currently Active DHCP Leases" table.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

replace  `.html()` call with `.text()` and chain `.css()`
` $("td:eq(3)", row).text("Unknown").css("font-style", "italic");`

This would also address concerns in #1434 

As to why this is happening, it's unclear.  This is the appropriate use of the `.html()` method, however there is this note in the jQuery documentation:
> This method uses the browser's innerHTML property. Some browsers may not generate a DOM that exactly replicates the HTML source provided.

**Comment by yubiuser** [comment] 2020-07-22 16:18
Proposed fix
https://github.com/pi-hole/AdminLTE/pull/1509

**Comment by yubiuser** [comment] 2020-07-22 16:50
You're fixing the wrong spot.

`network.js` is not used in `admin/settings.php?tab=piholedhcp` but instead in `/admin/network.php`

**Comment by loeffelpan** [comment] 2022-01-10 18:06
@yubiuser Your fix #1509 seems not to work. I use adminLTE 5.10.1 from yesterday an it shows `<i>unknown</i>` in DHCP lease table. Can you please take a look at your fix?

**Comment by yubiuser** [comment] 2022-01-10 18:26
The fix worked back then, but some other place must have been changed so that the issue was re-introduced. We'll take a look

**Comment by yubiuser** [comment] 2022-01-23 16:27
Closing as duplicate of https://github.com/pi-hole/AdminLTE/issues/1513

**Closed as completed by yubiuser** 2022-01-23 16:27 UTC
Labels: Bug
