### ISSUE TITLE
3rd party apps cannot communicate with PiHole using AdminLTE 5.10.1 API

### ISSUE THREAD

**Issue by CanonCan** [pi-hole/web#2066] opened 2022-01-10 15:13 UTC
### Versions

 Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)

### Platform

- OS and version:  
- 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

### Expected behavior

all third part browser extensions using API to communicate with Pihole broke once Pihole Web updated to 5.10.1

### Steps to reproduce
tird party appp say Pihole is disabled when it is in face not disabled and enabling them doesnt work

**Comment by yubiuser** [comment] 2022-01-10 18:24
> all third part browser extensions using API to communicate with Pihole broke once Pihole

Please be more specific

**Comment by CanonCan** [comment] 2022-01-10 19:14
The third party plugins don't work at all anymore they register off or disconnected.

**Comment by PromoFaux** [comment] 2022-01-10 19:16
In which case:

Duplicate of https://github.com/pi-hole/AdminLTE/issues/2048

and (should be) fixed in next release

**Closed as completed by PromoFaux** 2022-01-10 19:16 UTC

**Comment by CanonCan** [comment] 2022-01-10 19:36
Thanks that's what the developer of the plug-in told me too is there an ETA when this is expected? I use the third-party app rather than logging into pie hole directly to test various domains when they're being blocked

**Comment by PromoFaux** [comment] 2022-01-10 19:55
[Soon™](https://wowwiki-archive.fandom.com/wiki/Soon)

**Comment by CanonCan** [comment] 2022-01-10 20:07
I find it funny because flutter hole for Android still works using the API call
  

  

  
  
 Sincerely,  
  

  
Michael
  
  
  
  
  
  
>
