### ISSUE TITLE
Top Blocked Domains showing domains which aren't blocked

### ISSUE THREAD

**Issue by TheULi** [pi-hole/web#1740] opened 2021-02-16 16:10 UTC
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform

- OS and version:  Ubuntu 20.04

- Platform:  VMware

### Expected behavior

Top Blocked Domains should only shows domains which are blocked.

### Actual behavior / bug

Top Blocked Domain shows domain which aren't blocked. A query for the domain shows that it isn't blocked. There is no blocklist loaded.

## Debug Token

- URL:  https://tricorder.pi-hole.net/x142yfxiio

**Comment by TheULi** [comment] 2021-02-16 18:07
Hi,
you are right, there a some custom lists, but all list are disabled in group management.
The dashboard shows 0 Queries blocked, 0% blocked, 0 Domain on Blocklist.
The graph on the dashboard shows also 0 blocked queries, but the graph in the "long-term data" shows blocked queries.

**Comment by TheULi** [comment] 2021-02-16 18:21
![1](https://user-images.githubusercontent.com/2726611/108104894-2dbc9c80-708c-11eb-98d7-cdc0a8063d8f.PNG)
![2](https://user-images.githubusercontent.com/2726611/108104897-2e553300-708c-11eb-94bc-61ef1eb90ebf.PNG)
![3](https://user-images.githubusercontent.com/2726611/108104898-2e553300-708c-11eb-84ae-eec151d2a664.PNG)
![4](https://user-images.githubusercontent.com/2726611/108104899-2eedc980-708c-11eb-8c63-6e53cbd3bd19.PNG)

**Comment by dschaper** [comment] 2021-02-16 18:48
Who is your upstream and do they block domains? Can you check for one of the blocked domains and see if the upstream is returning an IP address or a block?

**Comment by TheULi** [comment] 2021-02-16 18:59
Upstream is a Sophos SG firewall.
I can't find any issue in the dns resolution of the "blocked" domains.

`administrator@pihole:~$ nslookup global.asimov.events.data.trafficmanager.net 192.168.153.1
Server:         192.168.153.1
Address:        192.168.153.1#53

Non-authoritative answer:
global.asimov.events.data.trafficmanager.net    canonical name = skypedataprdcoluks04.cloudapp.net.
Name:   skypedataprdcoluks04.cloudapp.net
Address: 52.114.88.28

administrator@pihole:~$ nslookup settingsfd-geo.trafficmanager.net 192.168.153.1           
Server:         192.168.153.1
Address:        192.168.153.1#53

Non-authoritative answer:
settingsfd-geo.trafficmanager.net       canonical name = settingsfd-prod-weu1-endpoint.trafficmanager.net.
Name:   settingsfd-prod-weu1-endpoint.trafficmanager.net
Address: 51.124.78.146
`

Are the "top blocked domains" also counted in the "top domains" ?

**Comment by yubiuser** [comment] 2021-02-16 19:03
Click on one of the bar in the long term database and see which query is blocked and for what reason.

**Comment by TheULi** [comment] 2021-02-16 19:08
![5](https://user-images.githubusercontent.com/2726611/108109731-97d84000-7092-11eb-98d4-a7c1ffa43686.PNG)

That's wired...
If you check all "blocked" boxes, there is no output. like the previous picture.
But in the "permit" filter there are blocks? strange

**Comment by TheULi** [comment] 2021-02-16 19:11
@yubiuser I checked all 127 queries in the list... all shows a green OK.

![6](https://user-images.githubusercontent.com/2726611/108110139-21880d80-7093-11eb-8ae8-7961b24859a5.PNG)

**Comment by TheULi** [comment] 2021-02-16 19:34
Queries with "OK (already forwarded)" are counted as queries blocked.
Queries with "Retried" are also counted as queries blocked.
Why?

**Comment by yubiuser** [comment] 2021-02-17 18:26
I can confirm the behavior!
In my long-term database I have 19 "blocked" queries and 19 green "Ok (already forwarded)" domains for yesterday.

**Comment by yubiuser** [comment] 2021-02-17 21:16
The issue is here
https://github.com/pi-hole/AdminLTE/blob/989e1ba0ca9f31570ea92a3139211d83cdcbd344/scripts/pi-hole/js/db_queries.js#L149

With the new query types, not everything >10 is blocked 
https://docs.pi-hole.net/database/ftl/#supported-status-types

**Comment by TheULi** [comment] 2021-02-18 20:39
@yubiuser Your code change isn't enough. That fixes only the long term query, but neither the long term graphics nor the log term top list.

**Comment by yubiuser** [comment] 2021-02-18 20:49
Thanks. I already suspected so and there was a report on discourse about wrong top lists.

I think I already know what to fix, might need one or two days

**Comment by yubiuser** [comment] 2021-02-19 05:58
Should be fixed now.

**Comment by yubiuser** [comment] 2022-01-08 06:24
Should be fixed since
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-8-web-v5-5-and-core-v5-3-released/46237/1

**Closed as completed by yubiuser** 2022-01-08 06:24 UTC
