### ISSUE TITLE
FTLPORT has no impact for the web interface

### ISSUE THREAD

**Issue by Adi146** [pi-hole/web#2221] opened 2022-06-07 22:08 UTC
### Versions

- Pi-hole:  v5.10
- AdminLTE:  v5.12
- FTL:  v5.15

### Platform

- OS and version:  Ubuntu 21.04

- Platform:  Docker

### Expected behavior

When changing the `FTLPORT`, the web interface should use the new port.

### Actual behavior / bug

The FTLPORT is not used and the web interface show that DNS service is not running.

### Steps to reproduce

1. Setup a new instance
2. Change the FTLPORT in /etc/pihole/pihole-FTL.conf to for example 4710
3. Restart Pi Hole
4. Go to the web interface

## Debug Token

- URL:  https://tricorder.pi-hole.net/sCg21cLY/

### Screenshots

![image](https://user-images.githubusercontent.com/10218047/172491221-7c6b5605-ac3b-462b-9269-aac2dab4c4f8.png)

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment] 2022-06-07 22:24
Your debug log shows FTL is using the selected port:
```
Listening on port 4710 for incoming IPv4 telnet connections
```

Does it work using the default port (removing this config)?

**Comment by Adi146** [comment] 2022-06-07 23:01
Yes it is working without the config. Here is a debug log for this case: https://tricorder.pi-hole.net/kdvOGYyf/
When using netstat I can see that FTL is also creating the correct socket but it seems like the web interface still tries to use the default port.

**Comment by rdwebdesign** [comment] 2022-06-07 23:12
I think I know where the problem is. When it's fixed, I will post a message here.

**Comment by yubiuser** [comment] 2022-06-08 07:12
PR https://github.com/pi-hole/AdminLTE/pull/2222 fixes the issue. Thanks for reporting. It will be part of the next Pi-hole release.

**Comment by Adi146** [comment] 2022-06-08 09:00
Great, thank you for the quick fix

**Closed as completed** 2022-07-07 19:41 UTC
Labels: Fixed In Next Release, Bug: Confirmed
