### ISSUE TITLE
Restoring Local DNS Records with Teleporter fails

### ISSUE THREAD

**Issue by mjmccans** [pi-hole/web#1555] opened 2020-08-13 02:30 UTC
### Versions
- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Raspberry Pi

### Expected behavior

Local DNS Records are restored when using the Teleporter restore functionality.

### Actual behavior / bug

An HTTP ERROR 500 is displayed, only the first Local DNS Record is restored, and the logs include the following error "PHP Fatal error:  Cannot redeclare error() (previously declared in /var/www/html/admin/scripts/pi-hole/php/func.php:126) in /var/www/html/admin/scripts/pi-hole/php/func.php on line 126" 

### Steps to reproduce

1. Backup pi-hole instance using the Teleporter feature that includes Local DNS Records
2. Attempt to restore the backup created in 1 on a second pi-hole instance, selecting Local DNS Records to be restored
3. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/1zovbfkc6v

**Comment by modem7** [comment] 2020-08-16 04:20
Aye, it's not just local DNS records unfortunately either. 

https://github.com/pi-hole/AdminLTE/issues/1537

**Comment by yubiuser** [comment] 2020-08-16 06:31
Closing as duplicate of https://github.com/pi-hole/AdminLTE/issues/1537

**Closed as completed by yubiuser** 2020-08-16 06:31 UTC
Labels: Duplicate
