### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by L1qu1d1c3** [pi-hole/web#1615] opened 2020-10-27 09:23 UTC
### Versions

- Pi-hole version is v5.1.2 (Latest: v5.1.2)
- AdminLTE version is v5.1.1 (Latest: v5.1.1)
-  FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  Linux raspberrypi 4.19.75-v7+ pi-hole/pi-hole#1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

- Platform:  Linux raspberrypi 4.19.75-v7+ pi-hole/pi-hole#1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

### Expected behavior

Expected: Login process works and takes me to the dashboard

### Actual behavior / bug

When I try to log in, I insert my password but I'm taken back to the login screen. If I insert an incorrect password, the error message appears that the password is incorrect.

### Steps to reproduce

Go to admin page, try to log in

## Debug Token

- URL:  https://tricorder.pi-hole.net/d3wp1dq97p

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context
See attached zip with a video of the bug

[Screen Recording 2020-10-27 at 8.16.50 pm.mov.zip](https://github.com/pi-hole/pi-hole/files/5444202/Screen.Recording.2020-10-27.at.8.16.50.pm.mov.zip)

_Add any other context about the problem here._

**Comment by PromoFaux** [comment] 2020-10-27 09:53
Possibly a duplicate of #1614 ...

What browser are you using? Can you try logging in with the browser's developer tools open, and see if anything unusual shows up? Can you also try opening in incognito/private browsing mode, and try another browser if possible.

**Comment by churchofnoise** [comment] 2020-10-27 19:17
Same issue here, on following branches:

- AdminLTE: new/FTL_is_my_new_home

- FTL: new/http

- Core: dev

Tried on

- laptop:

> - Firefox 82.0 (normal and Private browsing),
> 
> - latest Edge and Internet Explorer
- phone: Samsung Internet

same issue on all.

**Comment by churchofnoise** [comment] 2020-10-28 14:53
Found a work-around on the new/FTL_is_my_home branch of AdminLTE: usually, you would log on by going to pi.hole:8080/admin, in which case the error occurs. However, when you just go to pi.hole/admin, the problem does **not** occur! Afterwards, you can just add :8080 and the interface is functional. Hope this helps pinpoint the cause / solution!

**Comment by PromoFaux** [comment] 2020-10-28 15:03
Just FYI regards `FTL_is_my_new_home`, nothing (apart from the dashboard) is working properly on that branch right now - it's very much a work in progress - and we still have a ways to go before it is supportable, so we have to assume that anything seen on that branch is not for the same reason as a more stable branch. If that makes sense!

**Comment by churchofnoise** [comment] 2020-10-28 15:17
> 
> 
> Just FYI regards `FTL_is_my_new_home`, nothing (apart from the dashboard) is working properly on that branch right now - it's very much a work in progress - and we still have a ways to go before it is supportable, so we have to assume that anything seen on that branch is not for the same reason as a more stable branch. If that makes sense!

Absolutely aware of that, just thought it might be of help to you guys 👍

**Comment by L1qu1d1c3** [comment] 2020-11-05 00:24
> Possibly a duplicate of #1614 ...
> 
> What browser are you using? Can you try logging in with the browser's developer tools open, and see if anything unusual shows up? Can you also try opening in incognito/private browsing mode, and try another browser if possible.

I'm using Firefox on a Mac. But I've also tried on Safari on iPhone 12 - same issue.
I opened the developer tools and there are no errors popping up, only a CSS warning for the zoom property, but that's normal. All HTTP requests return 200.

**Closed as completed** 2022-01-13 21:03 UTC
Labels: Submitter Attention Required
