### ISSUE TITLE
Domin incorrectly added to WhiteList

### ISSUE THREAD

**Issue by d1964b** [pi-hole/web#1755] opened 2021-03-03 20:09 UTC
### Versions

- Pi-hole:  5,2,4
- AdminLTE:  5.4
- FTL:  5.7

### Platform

- OS and version:  Linux 4.19.107-Unraid x86_64

- Platform:  Unraid

### Expected behavior

Select 'Blacklist' button on Recent Queries view for an allowed domain , expected domain to be added to 'Blacklist'

### Actual behavior / bug

Select 'Blacklist' button on Recent Queries view for an allowed domain , domain  added to 'Whitelist'

### Steps to reproduce

1. Go to 'Query View'
2. Click on 'Blacklist' button next to a currently allowed domain
3. See popup window showing domin added to Whitelist , Open 'Whitelist; view to confim this

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment] 2021-03-03 20:12
Please upload a debug log and post **just the  token** that is generated after the log is uploaded by running the following command from the Pi-hole host terminal:
```
pihole -d
```
or do it through the Web interface:

***Tools > Generate Debug Log***

**Comment by d1964b** [comment] 2021-03-03 20:24
Sorry
Debug Log: https://tricorder.pi-hole.net/o71makdky4

**Comment by dschaper** [comment] 2021-03-03 21:17
Your debug log shows domains added to both the black and white lists via the Query Log.

Can you tell us a domain that you think should be on the blacklist and one that should be on the whitelist so that we can see if they are listed correctly in the database?

**Comment by d1964b** [comment] 2021-03-03 21:35
See below , as seen from recent query list
![unwanted domain](https://user-images.githubusercontent.com/31854979/109874738-68ffc380-7c67-11eb-8005-c083ac9a1ed3.JPG)
and appearance on Whitelist view after pressing Blacklist button:
![Whitelist view](https://user-images.githubusercontent.com/31854979/109875361-49b56600-7c68-11eb-8170-a6779c80d2ce.JPG)

**Comment by dschaper** [comment] 2021-03-03 21:51
I'm not able to duplicate this:

![Screenshot 2021-03-03 134500](https://user-images.githubusercontent.com/2782850/109876482-b60f7580-7c26-11eb-9619-968d7ff386ca.png)
![Screenshot 2021-03-03 134505](https://user-images.githubusercontent.com/2782850/109876489-b90a6600-7c26-11eb-9c2d-f59f18fcd0ea.png)
![Screenshot 2021-03-03 134753](https://user-images.githubusercontent.com/2782850/109876814-10a8d180-7c27-11eb-96c6-80066f541efa.png)

The debug log is showing some issues with the networking configuration. How are you running this on unraid, as a docker container or as VM image?

I see a number of errors in the `lighttpd` log, one of which is at the same time as your Blacklist entry. 

```plain
2021-03-03 20:19:34: (mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Undefined offset: 2 in /var/www/html/admin/api_FTL.php on line 107
```

**Comment by d1964b** [comment] 2021-03-03 22:01
I'm running it in a Docker container , The actual filtering behaviour of Pi-Hole works perfectly well i.e. what should be blocked is etc.

**Comment by PromoFaux** [comment] 2021-03-04 08:46
I had a hunch, just from looking at the screenshots shared by @d1964b.. and I am now able to reproduce this every time...

Let's see if anyone else can see what's happening in this gif 

![whitelist](https://user-images.githubusercontent.com/1998970/109936681-0f7ab180-7cc6-11eb-9937-f1c7d84b48f8.gif)


I'll try and dig into this later but:

It happens on queries marked as "already forwarded"


Anyone is more than welcome to beat me to this if they can :)

**Comment by d1964b** [comment] 2021-03-04 10:54
@PromoFaux , Yes that is what I see , thanks  for confirming it's not just me !

**Comment by WorldWideWebDev** [comment] 2021-03-04 11:05
@PromoFaux from you GIF i see that you are clicking on the "Remove" (Button in red with a circle and strike through it)  from blacklist button and Query is then being sent to the Whitelist.   What are you expecting other than removing it from the Blacklist to happen?? Im confused with this whole bug post.

**Comment by PromoFaux** [comment] 2021-03-04 14:53
@worldwidewebdev OK, I see where you might be confused - and actually I see where we might even have some room for improvement based on your confusion. Ignore the icon in this case (but certainly we can look at making this button even more clear in v6.0 (tagging @DL6ER) ..) 

But yeah, it's not a "remove" button


What is supposed to happen, when pressing the button that says "blacklist", is that the domain gets added to the blacklist. This works on most of the queries, but something has been missed the new query type of "already forwarded" was added.

**Comment by WorldWideWebDev** [comment] 2021-03-04 15:10
@PromoFaux  Sorry i was obviously confused also.  I was working on the blacklist and if from within the blacklist i click on that button (now i really don't know what to call the button)  the domain was sent to the whitelist.. But if i am in the query log area where the domains are listed in green, and i click the button, they are sent to the blacklist. I cannot reproduce what you have here in the GIF. Sorry for the confusion.  My post was actually for nothing..Regards
https://imgur.com/T8G1mSe
https://imgur.com/9bbNNv1

**Comment by PromoFaux** [comment] 2021-03-04 15:12
> I'll try and dig into this later but:
> 
> It happens on queries marked as "already forwarded"

As above - it only happens on entries where the query type is "OK (Already forwarded)" - look closely at my GIF, and the OP's screenshots :)

**Comment by WorldWideWebDev** [comment] 2021-03-04 15:21
Yes i can confirm if it is (Already Forwarded) i can reproduce the issue....,

 Thanks  you guys..!!

Shoot me now!! lol

**Comment by DL6ER** [comment] 2021-03-04 17:21
I would like to remove these buttons for longer, is now the time to do this? Reason is that we could very well use the space for other things.

If we keep them, we could remove the icon as the text and color should be enough to understand what will happen when clicking the button.

**Comment by yubiuser** [comment] 2021-03-04 18:51
> use the space for other things

What do you have in mind?

**Comment by DL6ER** [comment] 2021-03-05 09:52
Actually, looking again at the table, the best would be empty space. We've seen quite a few issues where people were wondering about scrollbars appearing on tablets, like so:

![Screenshot at 2021-03-05 10-38-23](https://user-images.githubusercontent.com/16748619/110097794-bd0dc380-7d9f-11eb-92e1-240e0d4695b5.png)

For the *actual* purpose of Pi-hole, I'd suggest a rather radical redesign of the table, like:
![Screenshot at 2021-03-05 10-47-16](https://user-images.githubusercontent.com/16748619/110098225-3ad1cf00-7da0-11eb-8fb6-725bd6662e0e.png)

The table will be much easier to use. And it won't get partially hidden on narrow screens.

We then add details dropdown menus like I already implemented for adlists in https://github.com/pi-hole/AdminLTE/pull/1673 (check out the screenshot over there). There we can include more details like the exact status (blocked because of what, link to the regex, cached, etc.), the used forward destination, the reply type, the reply time and we also have stuff for additional information such as remaining TTL and maybe some more interesting statistics we will add in the future.

Definitely something for v6.0, but I think it'll be a worthwhile simplification of the UI without actually loosing any information (we just hide them in a dropdown). I could even imagine the Query Log getting something like a `tail` function so you can see it as pretty log.

**Comment by yubiuser** [comment] 2021-03-05 19:41
Interesting. Looks a bit unfamiliar at first but could get used to it. v6.0 seem a good chance to cutting off old habits.

**Comment by DL6ER** [comment] 2021-03-05 20:27
@yubiuser already committed :-), will push once I added my keys to my new development machine

**Comment by yubiuser** [comment] 2021-03-16 19:39
@DL6ER What is strongly reduced with the lower number of columns is the ability to filter for information that is now hidden in the dropdown menu (like filtering for query status or reply). Of course not a fundamental necessity for an DNS ad blocker but was nice to have.

**Comment by DL6ER** [comment] 2021-03-16 21:25
Filtering will still be possible, we're working on a new "advanced search" feature that will replace the filter-by-click approach and overall increase usability. It'll that a bit of time until this is ready but you should only gain not loose anything by this.

**Comment by yubiuser** [comment] 2022-04-20 18:54
Released with https://github.com/pi-hole/AdminLTE/releases/tag/v5.12

**Closed as completed by yubiuser** 2022-04-20 18:54 UTC
Labels: Bug, Fixed In Next Release
