### ISSUE TITLE
Why can't I upgrade to AdminLTE v5.6?

### ISSUE THREAD

**Issue by 3DCoded** [pi-hole/web#2192] opened 2022-04-27 19:14 UTC
### Versions

- Pi-hole:  v5.10
- AdminLTE:  v5.12
- FTL:  v5/15

### Platform

Raspberry Pi OS Bullseye
- OS and version:  

Raspberry Pi 4B 4GB RAM Cortex A72
- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._
`pihole -v` shows AdminLTE at version v5.6 or newer after running `pihole -up`

### Actual behavior / bug

_A clear and concise description of what the bug is._

`pihole -v` shows AdminLTE at version v5.12 after running `pihole -up`

### Steps to reproduce

1. Go to terminal
2. Run `pihole -up`
3. Run `pihole -v`

## Debug Token
- URL:  

https://tricorder.pi-hole.net/bW0HaPN2/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment] 2022-04-27 19:18
Your debug token shows **you are using `v5.12`**.

Why do you want do **Downgrade** to `v5.6`?

**Comment by PromoFaux** [comment] 2022-04-27 19:49
Duplicate of https://github.com/pi-hole/AdminLTE/issues/2190

Please continue discussion there (closed threads can still receive comments). There is no need for a new issue thread, closing and locking this one :)

**Closed as completed by PromoFaux** 2022-04-27 19:49 UTC
