### ISSUE TITLE
Dark theme is not applied on .user-body at dropdown-menu on navbar

### ISSUE THREAD

**Issue by anwiese** [pi-hole/web#2763] opened 2023-10-18 08:56 UTC
### Versions

- Pi-hole version is development-v6 v5.17.1-164-ged0dfa8b (Latest: v5.17.2)
- web version is development-v6 v5.19-318-gf305d2d4 (Latest: v5.20.2)
- FTL version is development-v6 vDev-188ddf6 (Latest: v5.23)  

### Platform
- OS and version: Raspberry Pi OS Bookworm  
- Platform:  Raspberry Pi 3 Model B

### Expected behavior

Dark theme should apply on all elements of the dropdown menu in the top right corner of the web interface.

### Actual behavior / bug

The dark theme is not applied on the CSS element .user-body. The value background-color: #272c30; is missing. It only exists at the element user-footer.

### Steps to reproduce

1. Click on the dropdown menu in the top right corner

## Debug Token

- URL:  https://tricorder.pi-hole.net/BFQqUbxJ/

### Screenshots

![image](https://github.com/pi-hole/web/assets/11884694/bdd9ec3e-f68d-463d-b3d6-f75e950da247)

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment] 2023-10-18 17:39
> The dark theme is not applied

Which theme are you using?
![image](https://github.com/pi-hole/web/assets/1385443/ac1293bb-7dfc-43da-82ef-ae6bb7efa750)

I can't reproduce the issue using our dark themes (Midnight, Deep Midnight, High Contrast Dark and LCARS).

![dark_themes](https://github.com/pi-hole/web/assets/1385443/b14eb42c-17f3-47f7-b8ed-330e1defc397)

Also, which browser? Do you see the same on different browsers/devices?

**Comment by anwiese** [comment] 2023-10-18 18:49
I used Chrome 118.0.5993.71 on Windows 11 22H2 with the theme "Pi-hole auto". In Windows the Dark theme is used. When i switch to "Pi-hole midnight", everthing works as expected. On an iPad mini 6 with iPad OS 17.0.3 and the dark theme enabled, I can reproduce the error with Safari and the dark theme of the device when using the "Pi-hole auto" theme.

When I check the Dev Tools in the Chrome Browser it looks like the browser is loading both default-dark.css and default-light.css while using "Pi-hole auto" and a dark theme of the operating system. The declaration seems to come from the loaded default-light.css. When I use the day theme or midnight theme, only the corresponding css file is loaded in the browser. 

![Screenshot 2023-10-18 204743](https://github.com/pi-hole/web/assets/11884694/1d97c9dc-37c9-4f14-b0e0-84f2a21fcba8)

**Comment by rdwebdesign** [comment] 2023-10-18 20:03
Thanks.

I tested on Firefox using dark mode. The theme `Pi-hole auto` is showing the same issue.

It's a simple fix.

**Comment by rdwebdesign** [comment] 2023-10-20 00:52
Fixed in `development-v6`.

**Closed as completed by rdwebdesign** 2023-10-20 00:52 UTC
Labels: Pi-hole v6.0
