### ISSUE TITLE
"Disable query logging" not working

### ISSUE THREAD

**Issue by valfr** [pi-hole/web#1496] opened 2020-07-16 17:16 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`
---
**Expected behavior:**

In admin panel under Settings, clicking on "Disable query logging" should be not logging clients request.

**Actual behavior:**

clients request are still logged, under dashboard we see all requests

**Steps to reproduce:**

Upgrading with 5.1.1, clicking on "Disable query logging"

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

n8c1ehirdr

**Comment by valfr** [comment] 2020-07-16 17:43
Hello, 
After checking "no query instructions" are correctly applied to files /etc/pihole/setupVars.conf & /etc/dnsmasq.d/01-pihole.conf.
However logging is still available ...

**Comment by queeup** [comment] 2020-08-19 10:02
Same here. I can't disable query logging.

**Comment by queeup** [comment] 2020-09-12 19:06
My sdcard wearing out. Please do something about it.

**Comment by dschaper** [comment] 2020-09-12 19:09
Buy a less crappy SDCard.

**Comment by jfb-pihole** [comment] 2020-10-30 01:36
Queries are logged in two places.
(1) The dnsmasq log at /var/log/pihole.log.  This is controlled by the "query logging" toggle.
(2) The long term database at /etc/pihole/pihole-FTL.db.  Logging to this database is controlled by your privacy settings and your setting for MAXDBDAYS in file /etc/pihole/pihole-FTL.conf.  Data from the long term database is used to repopulate the query log on FTL restart.  If you disable the database but don't increase your privacy settings, within 24 hours the query log will be fully repopulated and the information stored in memory only.

**Comment by yubiuser** [comment] 2022-01-13 20:27
This is not an issue about a malfunction but about interpreting the button. It's basically a duplicate of https://github.com/pi-hole/AdminLTE/issues/1151

**Closed as completed by yubiuser** 2022-01-13 20:27 UTC
Labels: Duplicate
