### ISSUE TITLE
Web app reporting core vDev and web vDev despite using production tags

### ISSUE THREAD

**Issue by fclaerho** [pi-hole/web#1851] opened 2021-07-25 09:30 UTC
### Versions

- Pi-hole version is in detached HEAD state at v5.3.1 (Latest: v5.3.1)
- AdminLTE version is in detached HEAD state at v5.5 (Latest: v5.5)
- FTL version is v5.8.1 (Latest: v5.8.1)

### Platform

- OS and version:  Ubuntu 18.04.5 LTS

- Platform:  Desktop PC

### Expected behavior

The installation process of pihole is fairly complicated and I've spent quite some time figuring out how to automate it and have a reproducible setup; I want a classic install so I'm not using the existing Docker image; this is overall possible, but mainly relies on undocumented features such as --unattended, etc.) To be reproducible, the process also needs to pin the version of pihole (or rather versions of the 3 components). Given the installation process relies on git repositories, this simply consists in checking out the appropriate git commits or tags, as already mentionned here https://discourse.pi-hole.net/t/how-do-i-revert-to-a-previous-version-of-pi-hole/7168

Once all of this is done, I would expect the web app to just report the tags I've explicitly checked out, in the footer.

### Actual behavior / bug

The web app / adminLTE is reporting a `vDev` version despite the repositories are checked out on production tags (see versions above.) And this is easy to understand looking at the code:

	if($web_branch !== "master") {
		$web_current = "vDev";
		$web_commit = $versions[1];
	}

In my /etc/pihole/localbranches, I have `HEAD HEAD master` and therefore, given HEAD != master, then we end up with `vDev`.

### Steps to reproduce

1. Proceed as detailed in https://discourse.pi-hole.net/t/how-do-i-revert-to-a-previous-version-of-pi-hole/7168 to checkout tags
2. Open Pihole web app and observe the versions reported in the footer.

## Debug Token

- URL:  

### Screenshots

![Screenshot 2021-07-25 at 11 28 56](https://user-images.githubusercontent.com/8522210/126894484-7d83eb87-0a64-45ec-90fa-37ddc5548395.png)

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment] 2021-07-25 15:10
Here's how it's going to be done in the `install.sh` for docker for the next release:

https://github.com/pi-hole/docker-pi-hole/blob/dev/install.sh

Note that here we `checkout master` and then `reset --hard [tag]`

I've updated the FAQ post, 

Also, automated shouldn't be _too_ complicated, to be honest. You could probably just run something similar to the docker containers `install.sh` but on bare metal.


Edit: Closing as not a bug - rather the web interface is displaying what it is supposed to when not on the `master` branch

**Closed as completed by PromoFaux** 2021-07-25 15:10 UTC

**Comment by fclaerho** [comment] 2021-07-26 05:18
Thanks for the link to the Docker install script, I didn't know that one and indeed it looks very similar to what I ended with, I'll check the differences.

As for the bug report, I still think what the UI report is debatable, but it's very minor and I can live with it; thanks for the reply!
