### ISSUE TITLE
2FA Does Not Work

### ISSUE THREAD

**Issue by NittanySeaLion** [pi-hole/web#2779] opened 2023-10-24 20:13 UTC
As reported on Discourse (https://discourse.pi-hole.net/t/sso-option/65791/2?u=blockhead), after enabling 2FA, the login screen does not unhide the totp box and allow entry of 2FA code. 

Forcing the totp box to appear does not solve problem. 

Perhaps an issue in FTL auth.c ?

**Comment by DL6ER** [comment] 2023-10-26 15:03
Thanks for your report.

> Perhaps an issue in FTL auth.c ?

Not, this is a web-only issue. This is an error that was introduced by a rearranging of code where the correct behavior for enabled TOTP seems to not have been checked. This is fixed by PR https://github.com/pi-hole/web/pull/2783

> Forcing the totp box to appear does not solve problem.

I could not reproduce this. When manually showing the input field (remove class `hidden`), TOTP login works for me even on the unfixed `developmet-v6` branch.

**Comment by NittanySeaLion** [comment] 2023-10-26 15:08
I can't rule out user error ;) will check when pushed over the weekend

**Comment by NittanySeaLion** [comment] 2023-10-29 18:06
I tested the fix, and it works for me. Enabling 2FA allows box to show up. Entering pw and 2FA credentials permits access. Disabling 2FA removes box.

**Closed as completed** 2023-10-31 03:15 UTC
Labels: Bugfix in progress, Pi-hole v6.0

**Comment by NittanySeaLion** [comment] 2023-10-31 03:16
@DL6ER fixed with PR 2783
