### ISSUE TITLE
Emtpy value for top blocked client on Dashboard

### ISSUE THREAD

**Issue by maddler** [pi-hole/web#2600] opened 2023-05-28 22:35 UTC
### Versions

- Pi-hole:  5.17
- AdminLTE:  5.20
- FTL:  5.23

### Platform

- OS and version:  Ubuntu Kinetic 22.10

- Platform:  x86_64

### Expected behavior

Hostname shown for all the entries in the "Top Clients (blocked only)" table.

### Actual behavior / bug

Some of the cells are empty.

### Steps to reproduce

1. Go to 'Dashboard'
2. Scroll to the Top Clients (blocked only)

## Debug Token

- URL:  https://tricorder.pi-hole.net/U0Lw0SEf/

### Screenshots

_If applicable, add screenshots to help explain your problem._
![Pi-hole - pihole2-2023-05-28 at 23 34 25](https://github.com/pi-hole/AdminLTE/assets/302261/779ef19f-267d-46b6-9293-5601ea8e627a)

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment] 2023-05-28 22:38
Found and fixed already in a hotfix :)

https://github.com/pi-hole/AdminLTE/releases/tag/v5.20.1

Please run `pihole -up` again

**Comment by rdwebdesign** [comment] 2023-05-28 22:38
Duplicate of https://github.com/pi-hole/AdminLTE/issues/2596

Already fixed.

Please update your web interface to `v5.20.1`

**Closed as completed** 2023-05-28 22:38 UTC

**Comment by maddler** [comment] 2023-05-28 22:46
Ah, my bad. Searched right after the update bud didn't spot anything. 
Thanks! 

________________________________
