### ISSUE TITLE
"Flush logs" flushes only the last 24 hours

### ISSUE THREAD

**Issue by zeus86** [pi-hole/web#1539] opened 2020-08-01 11:32 UTC
**In raising this issue, I confirm the following:** 
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
not applicable

---
**Expected behavior:**

"Flush logs" will... flush all the logs

**Actual behavior:**

"Flush logs" will only flush the logs of the past 24 hours. While it seems like all flushed in the Dashboard (because it shows the last 24 hours). It is actually not. I believe this is a bug and not intended. This is also not a caching Problem, because i restarted the host-os meanwhile, but i can see still all data from the beginning (with the exception of 2 24-hour periods, where i "flushed the logs").

**Steps to reproduce:**
* settings -> Flush logs -> yes
* Long-term data -> Graphics -> set time/date-range to something bigger than 1day, e.g. last 7 days.
![Screenshot_20200801_133145](https://user-images.githubusercontent.com/11415964/89100905-64d2a580-d3fb-11ea-8240-7923d0e17e32.png)

**Comment by yubiuser** [comment] 2020-08-01 11:39
There is a feature request for what you intend: https://discourse.pi-hole.net/t/request-statistic-reset/28167

Independently, if flushing only the last 24h is the intended behavior, the description at the button might need more clarification.

**Comment by zeus86** [comment] 2020-08-01 11:42
> There is a feature request for what you intend: https://discourse.pi-hole.net/t/request-statistic-reset/28167
> Independently, if flushing only the last 24h is the intended behavior, the description at the button might need more clarification.

If this is intended, there should be a way anyways to flush ALL logs from the Web-UI

**Comment by yubiuser** [comment] 2020-08-01 12:03
Then please vote to increase chances that it might be implemented one day ;-)

**Comment by yubiuser** [comment] 2020-08-04 16:02
Looking at the code: it is intended. Flushing only deletes the last 24h from the database

https://github.com/pi-hole/pi-hole/blob/56cd7c4d59ceb629a2170cd1c8ab78ef26366019/advanced/Scripts/piholeLogFlush.sh#L60

I'm closing the issue, as the question is answered and just the feature request remains. Please vote and discuss in the discourse topic linked above.

**Closed as completed by yubiuser** 2020-08-04 16:02 UTC
Labels: Discourse Feature Request
