### ISSUE TITLE
Hostname HTML not parsed in DHCP leases.

### ISSUE THREAD

**Issue by ToontjeM** [pi-hole/web#2099] opened 2022-01-23 15:19 UTC
### Versions
  Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)

### Platform
Intel NUC
Ubuntu 20.04 LTS

### Expected behavior
Hostnames in italic

### Actual behavior / bug
Hostnames with HTML tags.

### Screenshots
<img width="983" alt="Screenshot 2022-01-23 at 16 16 46" src="https://user-images.githubusercontent.com/98271783/150685528-daccb221-f031-4de3-bdb8-229475cb16dd.png">

**Comment by yubiuser** [comment] 2022-01-23 16:27
This was once fixed by https://github.com/pi-hole/AdminLTE/pull/1509 but the issue re-appeared. 

Closing as duplicate of https://github.com/pi-hole/AdminLTE/issues/1513

**Closed as completed by yubiuser** 2022-01-23 16:27 UTC
Labels: Bug
