### ISSUE TITLE
Incorrect Timestamp handling in web interface

### ISSUE THREAD

**Issue by thefinaldegree** [pi-hole/web#125] opened 2019-01-04 08:52 UTC
I have found an odd bug with the Web UI that doesn't appear to be related to the specific browser being used.

from pihole.log:

`Jan  4 21:46:10 dnsmasq[24189]: cached i.instagram.com is <CNAME>`

From the WebUI 'Query Log' page:

`2019-01-04 08:46:10	A	i.instagram.com	10.1.1.87	OK (forwarded)	CNAME`

My best guess is that it's using UTC time for some reason and not applying the correct timezone

```
pi@pi-hole3:~ $ date
Fri  4 Jan 21:51:20 NZDT 2019
pi@pi-hole3:~ $ date -u
Fri  4 Jan 08:51:22 UTC 2019
```

I'm not sure what else to leave here, but ask and I shall deliver.

**Comment by DL6ER** [comment] 2019-01-04 08:57
The we interface applies the timezone as asked for by **the client's** browser. Please check the timezone of the computer you're using to access the web interface. Maybe it is set configured to UTC and has then just be set to the local time. Although this looks okay at first glance, it will cause the Pi-hole (and all other webpages that display time and taking into account timezones) to show the wrong time.

Check also when accessing the web interface from different devices, e.g., mobile phones. They should be aware of the correct time and zone.

**Comment by Mcat12** [comment] 2019-01-04 20:11
I'm unable to reproduce this. @thefinaldegree, do you see this with the new web interface (this repo, unreleased), or the old one (https://github.com/pi-hole/AdminLTE, currently released)?

**Comment by Mcat12** [comment] 2019-02-15 04:18
Closing due to lack of a response.

**Closed by Mcat12** 2019-02-15 04:18 UTC
